In [ ]:
import numpy as np
import pandas as pd

data = pd.read_csv('/content/Social Media Engagement Dataset.csv')
data.head()

post_id            timestamp day_of_week   platform        user_id  \
0  kcqbs6hxybia  2024-12-09 11:26:15      Monday  Instagram  user_52nwb0a6   
1  vkmervg4ioos  2024-07-28 19:59:26      Sunday    Twitter  user_ucryct98   
2  memhx4o1x6yu  2024-11-23 14:00:12    Saturday     Reddit  user_7rrev126   
3  bhyo6piijqt9  2024-09-16 04:35:25      Monday    YouTube  user_4mxuq0ax   
4  c9dkiomowakt  2024-09-05 21:03:01    Thursday    Twitter  user_l1vpox2k   

               location language  \
0  Melbourne, Australia       pt   
1          Tokyo, Japan       ru   
2        Beijing, China       ru   
3        Lagos, Nigeria       en   
4       Berlin, Germany       hi   

                                        text_content  \
0  Just tried the Chromebook from Google. Best pu...   
1  Just saw an ad for Microsoft Surface Laptop du...   
2  What's your opinion about Nike's Epic React?  ...   
3  Bummed out with my new Diet Pepsi from Pepsi! ...   
4  Just tried the Corolla from Toyota. Absolutely...   

                   hashtags                        mentions  ...  \
0                     #Food                             NaN  ...   
1          #MustHave, #Food     @CustomerService, @BrandCEO  ...   
2  #Promo, #Food, #Trending                             NaN  ...   
3    #Reviews, #Sustainable      @StyleGuide, @BrandSupport  ...   
4          #Health, #Travel  @BrandSupport, @InfluencerName  ...   

  comments_count impressions  engagement_rate brand_name    product_name  \
0            701       18991          0.19319     Google      Chromebook   
1            359       52764          0.05086  Microsoft  Surface Laptop   
2            643        8887          0.45425       Nike      Epic React   
3            743        6696          0.42293      Pepsi      Diet Pepsi   
4            703       47315          0.08773     Toyota         Corolla   

      campaign_name  campaign_phase  user_past_sentiment_avg  \
0       BlackFriday          Launch                   0.0953   
1      PowerRelease     Post-Launch                   0.1369   
2       BlackFriday     Post-Launch                   0.2855   
3        LaunchWave          Launch                  -0.2094   
4  LocalTouchpoints          Launch                   0.6867   

   user_engagement_growth  buzz_change_rate  
0                 -0.3672              19.1  
1                 -0.4510             -42.6  
2                 -0.4112              17.4  
3                 -0.0167              -5.5  
4                  0.0807              38.8  

[5 rows x 28 columns]

In [ ]:
reviews = data['text_content'].values[:12000]
labels  = data['sentiment_label'].values[:12000]




In [ ]:
data['text_content'].loc[1039]


"Comparing Microsoft Surface Duo to the competition. Wouldn't recommend. #Fashion, #Sustainable Would love to get your feedback!"

In [ ]:
data['sentiment_label'].loc[1039]

'Negative'

In [ ]:
from collections import Counter

Counter(labels)

Counter({'Positive': 4839, 'Negative': 4854, 'Neutral': 2307})

In [ ]:

punctuation = '!"#$%&\'()*+,-./:;<=>?[\]^_`{|}~'

# get rid of punctuation
all_reviews = 'separator'.join(reviews)
all_reviews = all_reviews.lower()
all_text = ''.join([c for c in all_reviews if c not in punctuation])

# split by new lines and spaces
reviews_split = all_text.split('separator')
all_text = ' '.join(reviews_split)

# create a list of words
words = all_text.split()

<>:1: SyntaxWarning: invalid escape sequence '\]'
<>:1: SyntaxWarning: invalid escape sequence '\]'
/tmp/ipython-input-2748096650.py:1: SyntaxWarning: invalid escape sequence '\]'
  punctuation = '!"#$%&\'()*+,-./:;<=>?[\]^_`{|}~'


In [ ]:
# get rid of web address, twitter id, and digit
new_reviews = []
for review in reviews_split:
    review = review.split()
    new_text = []
    for word in review:
        if (word[0] != '@') & ('http' not in word) & (~word.isdigit()):
            new_text.append(word)
    new_reviews.append(new_text)

/tmp/ipython-input-2777777309.py:7: DeprecationWarning: Bitwise inversion '~' on bool is deprecated and will be removed in Python 3.16. This returns the bitwise inversion of the underlying int object and is usually not what you expect from negating a bool. Use the 'not' operator for boolean negation or ~int(x) if you really want the bitwise inversion of the underlying int.
  if (word[0] != '@') & ('http' not in word) & (~word.isdigit()):


In [ ]:

## Build a dictionary that maps words to integers
counts = Counter(words)
vocab = sorted(counts, key=counts.get, reverse=True)
vocab_to_int = {word: ii for ii, word in enumerate(vocab, 1)}

## use the dict to tokenize each review in reviews_split
## store the tokenized reviews in reviews_ints
reviews_ints = []
for review in new_reviews:
    reviews_ints.append([vocab_to_int[word] for word in review])

In [ ]:

# stats about vocabulary
print('Unique words: ', len((vocab_to_int)))  # should ~ 74000+
print()

# print tokens in first review
print('Tokenized review: \n', reviews_ints[:1])

Unique words:  322

Tokenized review: 
 [[7, 56, 1, 282, 8, 67, 111, 112, 113, 89, 21, 22, 23, 24, 2, 25]]


In [ ]:

# 2=positive, 1=neutral, 0=negative label conversion
encoded_labels = []
for label in labels:
    label = label.lower()   # normalize case
    if label == 'neutral':
        encoded_labels.append(1)
    elif label == 'negative':
        encoded_labels.append(0)
    elif label == 'positive':
        encoded_labels.append(2)
    else:
        raise ValueError(f"Unknown label: {label}")

encoded_labels = np.asarray(encoded_labels)



In [ ]:

encoded_labels

array([2, 0, 0, ..., 2, 1, 0])

In [ ]:

def pad_features(reviews_ints, seq_length):
    ''' Return features of review_ints, where each review is padded with 0's
        or truncated to the input seq_length.
    '''

    # getting the correct rows x cols shape
    features = np.zeros((len(reviews_ints), seq_length), dtype=int)

    # for each review, I grab that review and
    for i, row in enumerate(reviews_ints):
        features[i, -len(row):] = np.array(row)[:seq_length]

    return features


In [ ]:
seq_length = 70

features = pad_features(reviews_ints, seq_length=seq_length)

## test statements
assert len(features)==len(reviews_ints), "The features should have as many rows as reviews."
assert len(features[0])==seq_length, "Each feature row should contain seq_length values."

# print first 10 values of the first 30 batches
print(features[:10,:10])

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [ ]:
split_frac = 0.8

## split data into training, validation, and test data (features and labels, x and y)

split_idx = int(len(features)*split_frac)
train_x, remaining_x = features[:split_idx], features[split_idx:]
train_y, remaining_y = encoded_labels[:split_idx], encoded_labels[split_idx:]

test_idx = int(len(remaining_x)*0.5)
val_x, test_x = remaining_x[:test_idx], remaining_x[test_idx:]
val_y, test_y = remaining_y[:test_idx], remaining_y[test_idx:]

## print out the shapes of the resultant feature data
print("\t\t\tFeature Shapes:")
print("Train set: \t\t{}".format(train_x.shape),
      "\nValidation set: \t{}".format(val_x.shape),
      "\nTest set: \t\t{}".format(test_x.shape))

			Feature Shapes:
Train set: 		(9600, 70) 
Validation set: 	(1200, 70) 
Test set: 		(1200, 70)


In [ ]:
import torch
from torch.utils.data import TensorDataset, DataLoader

# create Tensor datasets
train_data = TensorDataset(torch.from_numpy(train_x), torch.from_numpy(train_y))
valid_data = TensorDataset(torch.from_numpy(val_x), torch.from_numpy(val_y))
test_data = TensorDataset(torch.from_numpy(test_x), torch.from_numpy(test_y))

# dataloaders
batch_size = 50

# make sure the SHUFFLE the training data
train_loader = DataLoader(train_data, shuffle=True, batch_size=batch_size)
valid_loader = DataLoader(valid_data, shuffle=True, batch_size=batch_size)
test_loader = DataLoader(test_data, shuffle=True, batch_size=batch_size)

In [ ]:
# obtain one batch of training data

dataiter = iter(train_loader)

# Correct way to get next batch:
sample_x, sample_y = next(dataiter)

print('Sample input size: ', sample_x.size())   # batch_size, seq_length
print('Sample input: \n', sample_x)
print()
print('Sample label size: ', sample_y.size())   # batch_size
print('Sample label: \n', sample_y)


Sample input size:  torch.Size([50, 70])
Sample input: 
 tensor([[  0,   0,   0,  ...,  18,  19,  20],
        [  0,   0,   0,  ..., 178,  77,  80],
        [  0,   0,   0,  ...,  14,   2,  15],
        ...,
        [  0,   0,   0,  ...,   2,  27,  28],
        [  0,   0,   0,  ...,  24,   2,  25],
        [  0,   0,   0,  ...,  14,   2,  15]])

Sample label size:  torch.Size([50])
Sample label: 
 tensor([2, 0, 0, 1, 0, 2, 0, 0, 0, 0, 2, 0, 1, 2, 2, 2, 2, 0, 2, 2, 2, 0, 0, 0,
        0, 0, 2, 2, 2, 0, 1, 0, 0, 2, 0, 1, 2, 2, 1, 0, 0, 2, 0, 1, 0, 0, 0, 2,
        1, 2])


In [ ]:
# First checking if GPU is available
train_on_gpu=torch.cuda.is_available()

if(train_on_gpu):
    print('Training on GPU.')
else:
    print('No GPU available, training on CPU.')

No GPU available, training on CPU.


In [ ]:
import torch.nn as nn

class SentimentRNN(nn.Module):
    """
    The RNN model that will be used to perform Sentiment analysis.
    """

    def __init__(self, vocab_size, output_size, embedding_dim, hidden_dim, n_layers, drop_prob=0.5):
        """
        Initialize the model by setting up the layers.
        """
        super(SentimentRNN, self).__init__()

        self.output_size = output_size
        self.n_layers = n_layers
        self.hidden_dim = hidden_dim

        # embedding and LSTM layers
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.lstm = nn.LSTM(embedding_dim, hidden_dim, n_layers,
                            dropout=drop_prob, batch_first=True)

        # dropout layer
        self.dropout = nn.Dropout(0.3)

        # linear and sigmoid layers
        self.fc = nn.Linear(hidden_dim, output_size)
        self.sig = nn.Sigmoid()


    def forward(self, x, hidden):
        """
        Perform a forward pass of our model on some input and hidden state.
        """
        batch_size = x.size(0)

        # embeddings and lstm_out
        x = x.long()
        embeds = self.embedding(x)
        lstm_out, hidden = self.lstm(embeds, hidden)

        # stack up lstm outputs
        lstm_out = lstm_out.contiguous().view(-1, self.hidden_dim)

        # dropout and fully-connected layer
        out = self.dropout(lstm_out)
        out = self.fc(out)
        # sigmoid function
        sig_out = self.sig(out)

        # reshape to be batch_size first
        sig_out = sig_out.view(batch_size, -1)
        sig_out = sig_out[:, -1] # get last batch of labels

        # return last sigmoid output and hidden state
        return sig_out, hidden


    def init_hidden(self, batch_size):
        ''' Initializes hidden state '''
        # Create two new tensors with sizes n_layers x batch_size x hidden_dim,
        # initialized to zero, for hidden state and cell state of LSTM
        weight = next(self.parameters()).data

        if (train_on_gpu):
            hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda(),
                  weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda())
        else:
            hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_(),
                      weight.new(self.n_layers, batch_size, self.hidden_dim).zero_())

        return hidden

In [ ]:
# Instantiate the model w/ hyperparams
# Instantiate the model w/ hyperparams
vocab_size = len(vocab_to_int) + 1
output_size = 3
embedding_dim = 200
hidden_dim = 128
n_layers = 2

net = SentimentRNN(vocab_size, output_size, embedding_dim, hidden_dim, n_layers)

print(net)   # <-- this prints the summary


SentimentRNN(
  (embedding): Embedding(323, 200)
  (lstm): LSTM(200, 128, num_layers=2, batch_first=True, dropout=0.5)
  (dropout): Dropout(p=0.3, inplace=False)
  (fc): Linear(in_features=128, out_features=3, bias=True)
  (sig): Sigmoid()
)


In [ ]:
# loss and optimization functions
lr=0.001

criterion = nn.BCELoss()
optimizer = torch.optim.Adam(net.parameters(), lr=lr)

In [ ]:
# training params
epochs = 20
counter = 0
print_every = 100
clip = 5  # gradient clipping

# move model to GPU, if available
if train_on_gpu:
    net.cuda()

net.train()
# train for some number of epochs
for e in range(epochs):
    # batch loop
    for inputs, labels in train_loader:
        counter += 1

        if train_on_gpu:
            inputs, labels = inputs.cuda(), labels.cuda()

        # initialize hidden state for current batch size
        h = net.init_hidden(inputs.size(0))

        # detach hidden state to prevent backprop through entire history
        h = tuple([each.data for each in h])

        # zero accumulated gradients
        optimizer.zero_grad()

        # get the output from the model
        output, h = net(inputs, h)

        # calculate the loss and perform backprop
        loss = criterion(output.squeeze(), labels.float())
        loss.backward()

        # gradient clipping
        nn.utils.clip_grad_norm_(net.parameters(), clip)
        optimizer.step()

        # loss stats
        if counter % print_every == 0:
            # Get validation loss
            val_losses = []
            net.eval()
            for val_inputs, val_labels in valid_loader:

                if train_on_gpu:
                    val_inputs, val_labels = val_inputs.cuda(), val_labels.cuda()

                # init hidden state for validation batch
                val_h = net.init_hidden(val_inputs.size(0))
                val_h = tuple([each.data for each in val_h])

                val_output, val_h = net(val_inputs, val_h)
                val_loss = criterion(val_output.squeeze(), val_labels.float())

                val_losses.append(val_loss.item())

            net.train()
            print("Epoch: {}/{}...".format(e+1, epochs),
                  "Step: {}...".format(counter),
                  "Loss: {:.6f}...".format(loss.item()),
                  "Val Loss: {:.6f}".format(np.mean(val_losses)))


Epoch: 1/20... Step: 100... Loss: 159.948929... Val Loss: 180.596264
Epoch: 2/20... Step: 200... Loss: 174.689987... Val Loss: 180.405574
Epoch: 2/20... Step: 300... Loss: 159.336548... Val Loss: 178.482290
Epoch: 3/20... Step: 400... Loss: 199.394760... Val Loss: 178.476231
Epoch: 3/20... Step: 500... Loss: 150.784058... Val Loss: 178.368708
Epoch: 4/20... Step: 600... Loss: 211.383484... Val Loss: 178.401354
Epoch: 4/20... Step: 700... Loss: 171.749741... Val Loss: 177.097258
Epoch: 5/20... Step: 800... Loss: 167.998993... Val Loss: 177.148698
Epoch: 5/20... Step: 900... Loss: 204.080872... Val Loss: 177.381245
Epoch: 6/20... Step: 1000... Loss: 170.565887... Val Loss: 177.063654
Epoch: 6/20... Step: 1100... Loss: 189.640320... Val Loss: 176.934320
Epoch: 7/20... Step: 1200... Loss: 134.648834... Val Loss: 177.045632
Epoch: 7/20... Step: 1300... Loss: 176.034836... Val Loss: 176.918114
Epoch: 8/20... Step: 1400... Loss: 202.202728... Val Loss: 177.225662
Epoch: 8/20... Step: 1500... 

In [ ]:
# Get test data loss and accuracy

test_losses = [] # track loss
num_correct = 0

# init hidden state
h = net.init_hidden(batch_size)

net.eval()
# iterate over test data
for inputs, labels in test_loader:

    # Creating new variables for the hidden state, otherwise
    # we'd backprop through the entire training history
    h = tuple([each.data for each in h])

    if(train_on_gpu):
        inputs, labels = inputs.cuda(), labels.cuda()

    # get predicted outputs
    output, h = net(inputs, h)

    # calculate loss
    test_loss = criterion(output.squeeze(), labels.float())
    test_losses.append(test_loss.item())

    # convert output probabilities to predicted class (0 or 1)
    pred = torch.round(output.squeeze())  # rounds to the nearest integer

    # compare predictions to true label
    correct_tensor = pred.eq(labels.float().view_as(pred))
    correct = np.squeeze(correct_tensor.numpy()) if not train_on_gpu else np.squeeze(correct_tensor.cpu().numpy())
    num_correct += np.sum(correct)


# -- stats! -- ##
# avg test loss
print("Test loss: {:.3f}".format(np.mean(test_losses)))

# accuracy over all test data
test_acc = num_correct/len(test_loader.dataset)
print("Test accuracy: {:.3f}".format(test_acc))

Test loss: 193.047
Test accuracy: 0.259
